server:
  port: 8085

spring:
  application:
    name: config-server

  cloud:
    config:
      server:
        git:
          uri: https://github.com/AdmutheDipraj/Microservice_Config
          skip-ssl-validation: true






