server:
  port: 7575


spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/user/**
        - id: policy-service
          uri: lb://policy-service
          predicates:
            - Path=/policy/**

